<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>FAB619.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="CarthaSoft\**" />
    <EmbeddedResource Remove="CarthaSoft\**" />
    <None Remove="CarthaSoft\**" />
    <Page Remove="CarthaSoft\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\Assambly\Exploded View.svg" />
    <None Remove="Resources\Assambly\Main View.svg" />
    <None Remove="Resources\Assambly\Main View_files\bd0fac8be5a0025a_image_0.jpg" />
    <None Remove="Resources\Assambly\Main View_files\bd0fac8be5a0025a_image_1.jpg" />
    <None Remove="Resources\Assambly\STEP 1.svg" />
    <None Remove="Resources\Assambly\STEP 10.svg" />
    <None Remove="Resources\Assambly\STEP 11.svg" />
    <None Remove="Resources\Assambly\STEP 12.svg" />
    <None Remove="Resources\Assambly\STEP 13.svg" />
    <None Remove="Resources\Assambly\STEP 14.svg" />
    <None Remove="Resources\Assambly\STEP 15.svg" />
    <None Remove="Resources\Assambly\STEP 2.svg" />
    <None Remove="Resources\Assambly\STEP 3.svg" />
    <None Remove="Resources\Assambly\STEP 4.svg" />
    <None Remove="Resources\Assambly\STEP 5.svg" />
    <None Remove="Resources\Assambly\STEP 6.svg" />
    <None Remove="Resources\Assambly\STEP 7.svg" />
    <None Remove="Resources\Assambly\STEP 8.svg" />
    <None Remove="Resources\Assambly\STEP 9.svg" />
    <None Remove="Resources\BootLoader_microPython.uf2" />
    <None Remove="Resources\en.png" />
    <None Remove="Resources\fr.png" />
    <None Remove="Resources\Friendly.jpg" />
    <None Remove="Resources\Images\AtelierB.png" />
    <None Remove="Resources\Images\AtelierR.png" />
    <None Remove="Resources\Images\CarthaLogo.png" />
    <None Remove="Resources\Images\container.png" />
    <None Remove="Resources\Images\cover.png" />
    <None Remove="Resources\Images\fichierB.png" />
    <None Remove="Resources\Images\fichierR.png" />
    <None Remove="Resources\Images\HomeB.png" />
    <None Remove="Resources\Images\HomeR.png" />
    <None Remove="Resources\Images\Icons\learn.png" />
    <None Remove="Resources\Images\Icons\maze.png" />
    <None Remove="Resources\Images\Icons\mode.png" />
    <None Remove="Resources\Images\Icons\puzzle.png" />
    <None Remove="Resources\Images\Icons\python.png" />
    <None Remove="Resources\Images\Icons\tracer.png" />
    <None Remove="Resources\Images\moduleB.png" />
    <None Remove="Resources\Images\moduleR.png" />
    <None Remove="Resources\Images\up-arrow.png" />
    <None Remove="Resources\LineFollower.jpg" />
    <None Remove="Resources\logo.png" />
    <None Remove="Resources\ModulesImages\mod.png" />
    <None Remove="Resources\Obdidient.jpg" />
    <None Remove="Resources\ObstacleOvoid.jpg" />
    <None Remove="Resources\PowerOn.gif" />
    <None Remove="Resources\PowerOn2.gif" />
    <None Remove="Resources\robot.png" />
    <None Remove="Resources\robotD.png" />
    <None Remove="Resources\robotL.png" />
    <None Remove="Resources\robotR.png" />
    <None Remove="Resources\robotU.png" />
    <None Remove="Resources\Settings.ini" />
    <None Remove="Resources\STEP 1.png" />
    <None Remove="Resources\STEP 2.png" />
    <None Remove="Resources\STEP 3.png" />
    <None Remove="Resources\technical-drawing.png" />
    <None Remove="Resources\u2f\BootLoader_microPython.uf2" />
    <None Remove="Resources\u2f\MazeCode.uf2" />
  </ItemGroup>
  <ItemGroup>
    <Page Remove="Resources\StringResources-FR.xaml" />
    <Page Remove="Resources\StringResources.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="FAB619.ico" />
    <Content Include="Resources\Assambly\Exploded View.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\Main View.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\Main View_files\bd0fac8be5a0025a_image_0.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\Main View_files\bd0fac8be5a0025a_image_1.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 1.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 10.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 11.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 12.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 13.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 14.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 15.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 2.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 3.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 4.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 5.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 6.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 7.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 8.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Assambly\STEP 9.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\CarthaSoftLogo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\en.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\fr.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Friendly.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\Icons\maze.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\Icons\mode.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\Icons\puzzle.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\Icons\python.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\Icons\tracer.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\up-arrow.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\LineFollower.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Obdidient.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\ObstacleOvoid.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Settings.ini">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\Icons\CarthaLogo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\container.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Images\cover.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\ModulesImages\mod.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\PowerOn.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\PowerOn2.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\robot.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\robotL.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\robotU.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\robotD.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\robotR.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\STEP 1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\STEP 2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\STEP 3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\technical-drawing.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\u2f\Modes.uf2">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\u2f\MazeCode.uf2">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Images\Icons\learn.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.1.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
    <PackageReference Include="Syncfusion.SfProgressBar.WPF" Version="28.1.38" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="ToastNotifications" Version="2.5.1" />
    <PackageReference Include="ToastNotifications.Messages" Version="2.5.1" />
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="DMSkin.Core">
      <HintPath>Tools\DMSkin.Core.dll</HintPath>
    </Reference>
    <Reference Include="DMSkin.WPF">
      <HintPath>Tools\DMSkin.WPF.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\Fonts\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AdvancedProgramming\AdvancedProgramming.csproj" />
    <ProjectReference Include="..\BehaveProject\BehaveProject.csproj" />
    <ProjectReference Include="..\LearningProject\LearningProject.csproj" />
    <ProjectReference Include="..\MazeProject\MazeProject.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\StringResources-FR.xaml" />
    <Resource Include="Resources\StringResources.xaml" />
    <Content Include="Resources\u2f\BootLoader_microPython.uf2">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <!-- Embedded VPL (Coding under 6) graphics -->
    <Resource Include="Vpl\Assets\logo.png" />
    <Resource Include="Vpl\Assets\CarthaLogo.png" />
    <Resource Include="Vpl\Assets\robot.png" />
  </ItemGroup>
  <ItemGroup>
    <!-- 3D CarthaBot mascot for the VPL empty state (authored in Blender).
         Loaded from disk at runtime by HelixToolkit ModelImporter, so it must be
         Content copied next to the exe (not an embedded Resource). -->
    <Content Include="Vpl\Assets\carthabot_robot.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_robot.mtl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_exploded.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_exploded.mtl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <!-- VPL simulator playground (Blender-authored; the JSON manifest carries the
         exact gameplay coordinates the world was built with) -->
    <Content Include="Vpl\Assets\carthabot_simworld.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_simworld.mtl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_simworld.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_obstacle.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_obstacle.mtl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_coin.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_coin.mtl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_goalflag.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Vpl\Assets\carthabot_goalflag.mtl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Models\Classes\CustomDisplayPartErrSucc.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>